language: python

dist: trusty

addons:
  apt:
    packages:
      libc6-dev
      libtool
      libcfitsio3-dev
      libnova-dev
      libncurses5-dev
      libgraphicsmagick++1-dev
      libx11-dev
      docbook-xsl
      xsltproc
      libxml2-dev
      libarchive-dev
      python-numpy
      python-scipy
      python-pyfits
      python-matplotlib
      libxt-dev
      libfftw3-dev
      gnuplot-x11
      libjson-glib-dev
      libsoup2.4-dev
      pkg-config
      postgresql-server-dev-all
      postgresql
      libecpg-dev
      wget

python:
  - "2.7"
  - "3.4"
  - "3.5"

env:
  - PKG_CONFIG_PATH=`pwd`/erfa-1.2.0/build/lib/pkgconfig
  - PKG_CONFIG_PATH=''

install:
  - pip install lmfit

script:
  - cd checks && for x in check_python*; do ./$x; done && cd ..
  - if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then (wget https://github.com/liberfa/erfa/archive/v1.2.0.tar.gz && tar xzf v1.2.0.tar.gz && cd erfa-1.2.0/ && ./bootstrap.sh && ./configure --prefix=`pwd`/build && make install && cd .. && ./autogen.sh && ./configure && make && make check); fi
